version: "3.8"
services:
  csharp-simple-api-mariadb:
    network_mode: "host"
    image: mariadb:latest
    container_name: csharp-simple-api-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "123"
      MARIADB_DATABASE: "demo"
    ports:
      - 3306:3306
  #csharp-simple-api:
    ##depends_on:
      ##csharp-simple-api-mariadb:
        ##condition: service_healthy
    #ports:
      #- 8080:8080
    #container_name: csharp-simple-api
    #build:
      #context: .
    #extra_hosts:
        #- "host.docker.internal:host-gateway"
    #env_file: ./.env

